function robot_param = dynNS(u);
global l1 l2 l3 m1 m2 m3 Ixx1 Ixx2 Ixx3 Iyy1 Iyy2 Iyy3 Izz1 Izz2 Izz3 g;
q1 =u(1);
q2=u(4);
q3 =u(7);
dq1=u(2);
dq2=u(5);
dq3=u(8);
ddq1=u(3);
ddq2=u(6);
ddq3=u(9);

theta1 =(q1*(pi/180));
theta2 =(q2*(pi/180));
theta3 =(q3*(pi/180));


% % Kutle Merkezi MATRISI
M11= Izz1 + Izz2 + Izz3 + m3*(l3*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) + l2*cos(theta1) + (l3*(cos(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) - sin(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1))))/2)^2 + m3*(l3*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + l2*sin(theta1) + (l3*(cos(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + sin(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2))))/2)^2 + m2*((l2*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)))/2 + l2*cos(theta1))^2 + m2*((l2*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)))/2 + l2*sin(theta1))^2;
M12 = Izz2 + Izz3 + m3*(l3*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) + (l3*(cos(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) - sin(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1))))/2)*(l3*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) + l2*cos(theta1) + (l3*(cos(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) - sin(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1))))/2) + m3*(l3*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + (l3*(cos(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + sin(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2))))/2)*(l3*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + l2*sin(theta1) + (l3*(cos(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + sin(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2))))/2) + (l2*m2*((l2*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)))/2 + l2*cos(theta1))*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)))/2 + (l2*m2*((l2*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)))/2 + l2*sin(theta1))*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)))/2;
M13 = Izz3 + (l3*m3*(cos(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) - sin(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)))*(l3*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) + l2*cos(theta1) + (l3*(cos(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) - sin(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1))))/2))/2 + (l3*m3*(cos(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + sin(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)))*(l3*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + l2*sin(theta1) + (l3*(cos(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + sin(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2))))/2))/2;
M21 = Izz2 + Izz3 + m3*(l3*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) + (l3*(cos(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) - sin(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1))))/2)*(l3*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) + l2*cos(theta1) + (l3*(cos(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) - sin(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1))))/2) + m3*(l3*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + (l3*(cos(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + sin(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2))))/2)*(l3*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + l2*sin(theta1) + (l3*(cos(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + sin(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2))))/2) + (l2*m2*((l2*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)))/2 + l2*cos(theta1))*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)))/2 + (l2*m2*((l2*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)))/2 + l2*sin(theta1))*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)))/2;
M22 = Izz2 + Izz3 + m3*(l3*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + (l3*(cos(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + sin(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2))))/2)^2 + m3*(l3*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) + (l3*(cos(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) - sin(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1))))/2)^2 + (l2^2*m2*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1))^2)/4 + (l2^2*m2*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2))^2)/4;
M23 = Izz3 + (l3*m3*(cos(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + sin(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)))*(l3*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + (l3*(cos(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + sin(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2))))/2))/2 + (l3*m3*(cos(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) - sin(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)))*(l3*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) + (l3*(cos(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) - sin(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1))))/2))/2;
M31 = Izz3 + (l3*m3*(cos(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) - sin(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)))*(l3*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) + l2*cos(theta1) + (l3*(cos(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) - sin(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1))))/2))/2 + (l3*m3*(cos(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + sin(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)))*(l3*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + l2*sin(theta1) + (l3*(cos(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + sin(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2))))/2))/2;
M32 = Izz3 + (l3*m3*(cos(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + sin(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)))*(l3*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + (l3*(cos(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + sin(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2))))/2))/2 + (l3*m3*(cos(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) - sin(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)))*(l3*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) + (l3*(cos(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) - sin(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1))))/2))/2;
M33 = Izz3 + (l3^2*m3*(cos(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)) + sin(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)))^2)/4 + (l3^2*m3*(cos(theta3)*(cos(theta1)*cos(theta2) - sin(theta1)*sin(theta2)) - sin(theta3)*(cos(theta1)*sin(theta2) + cos(theta2)*sin(theta1)))^2)/4;

M=[M11 M12 M13; M21 M22 M32; M31 M32 M33];
robot_param=[M];
end
 